version: "3.9"
services:
    ## --------------------------------------------------
    ## | Backend - webserver service
    ## --------------------------------------------------
    sarveno_webserver:
        image: nginx:1.23.1
        container_name: sarveno_webserver
        restart: unless-stopped
        ports:
            - "8088:80"
        volumes:
            - ./:/var/www
            - ./.docker/sarveno_webserver/conf.d:/etc/nginx/conf.d
        depends_on:
            - sarveno_backend
        networks:
            - sarveno-network
    
    ## --------------------------------------------------
    ## | Backend - Php service
    ## --------------------------------------------------
    sarveno_backend:
        build:
            args:
                user: sarveno-user
                uid: 1000
            context: .
            dockerfile: .docker/sarveno_backend/Dockerfile
        container_name: sarveno_backend
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./.docker/sarveno_backend/config/php.ini:/usr/local/etc/php/php.ini
        networks:
            - sarveno-network
    ## --------------------------------------------------
    ## | Mysql - Database service
    ## --------------------------------------------------
    sarveno_mysql:
        container_name: sarveno-mysql
        hostname: sarveno-mysql
        build:
            context: .docker/sarveno_mysql
            dockerfile: Dockerfile
        environment:
            MYSQL_DATABASE: sarVenoDb
            MYSQL_USER: sarVenoUser
            MYSQL_PASSWORD: sarVenoPass
            MYSQL_ROOT_PASSWORD: sarVenoRootPass
        ports:
            - "3308:3306"
        volumes:
            - .docker/sarveno_mysql/data:/var/lib/mysql
        restart: always
        networks:
            sarveno-network:

networks:
    sarveno-network:
        driver: bridge

